// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package foobarbaz

// Injectors from container.go:

func initializeBaz() *Baz {
	foo := NewFoo()
	bar := NewBar(foo)
	baz := NewBaz(bar)
	return baz
}
