// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/ClareChu/collection/src/example/controller"
)

// Injectors from wire.go:

func Initialize() *controller.Iris {
	iris := controller.NewIris()
	return iris
}
