// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package db

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from dbwire.go:

func DataSourceInitialize() *DataSource {
	dataSource := NewDataSource()
	return dataSource
}
